// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbMx6JV0eRWUAwpF7rZisRTkuo31BYek',
    appId: '1:447102993595:web:47105780313771a0e2959e',
    messagingSenderId: '447102993595',
    projectId: 'intent-bc3cb',
    authDomain: 'intent-bc3cb.firebaseapp.com',
    storageBucket: 'intent-bc3cb.appspot.com',
    measurementId: 'G-1RKE5F027F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVuT2DbUdgw_C-g9XEijLSm3hQYFnvoXM',
    appId: '1:447102993595:android:f7547978b879ef4ae2959e',
    messagingSenderId: '447102993595',
    projectId: 'intent-bc3cb',
    storageBucket: 'intent-bc3cb.appspot.com',
  );
}
